version: '3.8'

services:
  app:
    image: mosonata/xef-m-web-front-img1:latest
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    networks:
      - webnet
    environment:
      NODE_ENV: production

networks:
  webnet: 