version: '3.8'

services:
  app:
    image: mosonata/xef-m-web-front-img1:latest
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - HOSTNAME=0.0.0.0
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: ingress
    networks:
      - webnet
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  webnet:
    driver: overlay
    attachable: true
