version: '3.8'

services:
  app:
    image: mosonata/xef-m-web-front-img1:latest
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 10s
    environment:
      - NODE_ENV=production
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    networks:
      - webnet

networks:
  webnet:
